# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facefinder', '0002_video_newvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='newVideo',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
