# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 01:18
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('facefinder', '0004_auto_20171204_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_roll_pitch_yaw',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
